// Reads curated Lucide icons from node_modules/lucide-static/icons/*.svg,
// normalizes each SVG, and emits:
//   - src/views/icons.rs — pub fn icon(name: &str) -> Safe<&'static str>
//
// Templates call icon("name") with no `|safe` because the function returns
// askama's Safe<_> marker. Islands (TSX) use lucide-preact directly; no
// generated TS file.

import { readFile, writeFile } from "node:fs/promises";

const ICON_NAMES = [
  "alert-circle",
  "alert-triangle",
  "arrow-left",
  "arrow-right",
  "at-sign",
  "calendar",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "circle",
  "circle-check",
  "circle-dot",
  "circle-x",
  "clipboard",
  "clipboard-check",
  "clock",
  "command",
  "copy",
  "download",
  "external-link",
  "eye",
  "eye-off",
  "file",
  "folder",
  "grid",
  "home",
  "image",
  "info",
  "key",
  "key-round",
  "layout-dashboard",
  "link",
  "link-2",
  "list",
  "lock",
  "lock-open",
  "log-in",
  "log-out",
  "mail",
  "moon",
  "more-horizontal",
  "more-vertical",
  "pencil",
  "phone",
  "plus",
  "qr-code",
  "refresh-cw",
  "save",
  "search",
  "settings",
  "shield",
  "shield-alert",
  "shield-check",
  "sliders-horizontal",
  "square-pen",
  "star",
  "sun",
  "tag",
  "terminal",
  "trash-2",
  "upload",
  "user",
  "user-plus",
  "user-x",
  "users",
  "users-round",
  "wifi",
  "x",
] as const;

const ICONS_DIR = "node_modules/lucide-static/icons";
const RUST_OUT = "src/views/icons.rs";

function normalizeSvg(raw: string): string {
  // Strip the license comment lucide adds at the top.
  let svg = raw.replace(/<!--[\s\S]*?-->/g, "").trim();

  // Collapse the multi-line attribute block onto one logical <svg ...> tag so
  // we can edit it. Lucide ships its files pretty-printed:
  //   <svg
  //     class="..."
  //     width="24"
  //     ...
  //   >
  // Match the opening <svg ...> up to its closing '>' (no '>' inside attributes).
  const openMatch = svg.match(/<svg\b[^>]*>/);
  if (!openMatch) {
    throw new Error("no <svg> open tag");
  }
  let openTag = openMatch[0];

  // Drop width="..." and height="..." so wrappers can size via CSS.
  openTag = openTag.replace(/\s+width="[^"]*"/g, "");
  openTag = openTag.replace(/\s+height="[^"]*"/g, "");
  // Force a single canonical class so wrappers can target it if needed.
  openTag = openTag.replace(/\s+class="[^"]*"/g, "");
  openTag = openTag.replace(/<svg\b/, `<svg class="lucide"`);
  // Collapse newlines / extra whitespace inside the tag.
  openTag = openTag.replace(/\s+/g, " ").replace(/\s*>$/, ">");

  svg = svg.replace(openMatch[0], openTag);
  // Collapse newlines between children too — keeps output compact.
  svg = svg.replace(/>\s+</g, "><").trim();
  return svg;
}

async function loadIcon(name: string): Promise<string> {
  const path = `${ICONS_DIR}/${name}.svg`;
  const raw = await readFile(path, "utf8");
  return normalizeSvg(raw);
}

function emitRust(icons: Map<string, string>): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/build-icons.ts — do not edit by hand.");
  lines.push("// Source: node_modules/lucide-static/icons/*.svg");
  lines.push("");
  lines.push("use askama::filters::Safe;");
  lines.push("");
  lines.push("/// Resolve a Lucide icon name to its raw SVG markup.");
  lines.push("/// Returns `Safe<&'static str>` so templates can write `{{ icon(\"name\") }}`");
  lines.push("/// without a trailing `|safe` filter. Unknown names render as empty.");
  // rustfmt would break the single-line match arms below into multi-line block
  // arms, which makes the file ~10x longer and creates churn the generator and
  // CI's `fmt --check` keep fighting over. The file is machine-generated; skip.
  lines.push("#[rustfmt::skip]");
  lines.push("pub fn icon(name: &str) -> Safe<&'static str> {");
  lines.push("    let svg = match name {");
  for (const [name, svg] of icons) {
    if (svg.includes('"#')) {
      throw new Error(`icon ${name} contains '"#' which breaks Rust raw strings`);
    }
    lines.push(`        ${JSON.stringify(name)} => r#"${svg}"#,`);
  }
  // Visible fallback so unknown icon names jump out during dev: a thick magenta
  // outlined square with a diagonal slash and a centred "?" mark.
  lines.push("        _ => r##\"<svg class=\"lucide\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"#ff00ff\" stroke=\"#ff00ff\" stroke-width=\"3\" stroke-linecap=\"square\" stroke-linejoin=\"miter\"><rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" fill=\"none\"/><line x1=\"2\" y1=\"22\" x2=\"22\" y2=\"2\"/><text x=\"12\" y=\"17\" text-anchor=\"middle\" font-family=\"monospace\" font-size=\"14\" font-weight=\"900\" fill=\"#ff00ff\" stroke=\"none\">?</text></svg>\"##,");
  lines.push("    };");
  lines.push("    Safe(svg)");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

const icons = new Map<string, string>();
for (const name of ICON_NAMES) {
  icons.set(name, await loadIcon(name));
}

await writeFile(RUST_OUT, emitRust(icons));

console.log(`wrote ${icons.size} icons to ${RUST_OUT}`);
